<?php

$lang = array(

	'other' => '其他',
	'app_connent_ok' => '通信成功 ',
	'app_connent_false' => '通信失败',

	'note_deleteuser' => '删除用户',
	'note_renameuser' => '重命名用户',
	'note_deletefriend' => '删除好友',
	'note_gettag' => '获取TAG',
	'note_getcreditsettings' => '获取应用积分设置',
	'note_updatecreditsettings' => '更新应用积分设置',
	'note_updateclient' => '更新应用缓存',
	'note_updatepw' => '更新用户密码',
	'note_updatebadwords' => '更新词语过滤列表',
	'note_updatehosts' => '更新域名解析列表',
	'note_updateapps' => '更新应用列表',
	'note_updatetagtemplate' => '更新标签模板设置',
	'note_list' => '通知列表',
	'note_test' => '测试',
	'note_delete' => '删除',
	'note_succeed' => '通知成功 ',
	'note_na' => '未通知',
	'note_false' => '通知失败',
	'note_times' => '次',

	'pm_from' => '来自',
	'pm_to' => '发送到',
	'pm_system' => '系统消息',
	'pm_date' => '时间',
	'pm_daterange_1' => '今天',
	'pm_daterange_2' => '昨天',
	'pm_daterange_3' => '前天',
	'pm_daterange_4' => '上周',
	'pm_daterange_5' => '更早',
	'pm_notitle' => '[无标题]',

	'user_add' => '添加用户',
	'user_delete' => '删除用户',
	'login' => '登录',
	'logout' => '退出',
	'app_add' => '添加新应用',
	'app_delete' => '删除应用',
	'app_edit' => '编辑应用',
	'setting_update' => '更新基本设置',
	'setting_register_update' => '更新注册设置',
	'pm_send' => '发送公共消息',
	'pm_delete' => '删除公共消息',
	'pm_clear' => '清理短消息',
	'badword_add' => '添加词语过滤',
	'badword_delete' => '删除词语过滤',
	'admin_add' => '添加管理员',
	'admin_pw_edit' => '修改创始人密码',
	'admin_priv_edit' => '修改管理员权限',
	'domain_add' => '添加域名解析',
	'domain_delete' => '删除域名解析',
	'credit_addexchange' => '更新积分兑换方案',
	'credit_deleteexchange' => '删除积分兑换方案',
	'credit_sync' => '同步应用的积分设置',
	'db_export' => '备份数据',
	'db_import' => '恢复数据',
	'db_delete' => '删除数据',
	'note_delete' => '删除通知',
	'note_send' => '补发通知',
	'dumpfile_exists' => '备份存在',
	'dumpfile_not_exists' => '备份不存在',
);