<?php
return array (
  'db_type' => 'mysql',
  'db_host' => '127.0.0.1',
  'db_name' => 'helpu',
  'db_user' => 'root',
  'db_pwd' => '123123',
  'db_port' => '3306',
  'db_prefix' => 'gxl_',
  'db_charset' => 'utf8',
  'default_theme' => 'gxlcms',
  'user_theme' => 'new',
  'site_name' => '做题累了来听书',
  'site_path' => '/',
  'site_url' => '/',
  'site_icp' => '粤ICP备88888888号',
  'site_email' => 'admin@admin.com',
  'site_keywords' => '听书',
  'site_description' => '听书',
  'site_hot' => '',
  'site_tongji' => '',
  'site_copyright' => '',
  'admin_order_type' => 'addtime',
  'admin_time_edit' => true,
  'admin_ads_file' => 'Runtime/ad',
  'url_num_admin' => '15',
  'home_pagenum' => '15',
  'url_html' => '0',
  'html_file_suffix' => '.html',
  'url_html_list' => '0',
  'url_tinglist' => '',
  'url_newslist' => '',
  'url_tingdata' => '',
  'url_newsdata' => '',
  'url_html_play' => '0',
  'url_play' => '',
  'url_special' => '',
  'url_specialdata' => '',
  'url_tingnewsdata' => '',
  'url_map' => '',
  'url_mytemplate' => '',
  'url_time' => '',
  'url_number' => '',
  'url_rewrite' => '0',
  'url_html_suffix' => '.html',
  'rewrite_tinglist' => '/$listdir/index$page',
  'rewrite_tingdetail' => '/$listdir/$pinyin/index',
  'rewrite_tingnews' => '/$pinyin/news/index$page',
  'rewrite_tingplay' => '/$listdir/$pinyin/$sid-$pid',
  'rewrite_tingsearch' => '/ting-search-wd-$wd-p-$page',
  'rewrite_tingtype' => '/$listdir/index_$page_$mcid_$lz_$year_$letter_$order_$area_$picm',
  'rewrite_tingtag' => '/tag-ting-wd-$wd-p-$page',
  'rewrite_newslist' => '/news-show-id-$id-p-$page',
  'rewrite_newsdetail' => '/news-read-id-$id',
  'rewrite_newssearch' => '/news-search-wd-$wd-p-$page',
  'rewrite_newstag' => '/tag-shown-wd-$wd-p-$page',
  'rewrite_speciallist' => '/special-show-p-$page',
  'rewrite_specialdetail' => '/special-read-id-$id',
  'rewrite_guestbook' => '/gb-show-p-$page',
  'rewrite_map' => '/map-show-id-$id-limit-$limit',
  'rewrite_mytemplate' => '/$id',
  'data_cache_type' => 'file',
  'data_cache_ting' => '0',
  'data_cache_news' => '0',
  'data_cache_special' => '0',
  'data_cache_tingforeach' => '0',
  'data_cache_newsforeach' => '0',
  'data_cache_specialforeach' => '0',
  'data_cache_all' => '0',
  'tmpl_cache_on' => false,
  'html_cache_on' => false,
  'html_cache_index' => '1',
  'html_cache_list' => '1',
  'html_cache_content' => '1',
  'html_cache_play' => '1',
  'html_cache_ajax' => '1',
  'upload_path' => 'flie',
  'upload_style' => 'Y-m-d',
  'upload_class' => 'jpg,gif,png,jpeg,mp3,m4a',
  'upload_http_down' => '5',
  'upload_http' => false,
  'upload_http_news' => '0',
  'upload_thumb' => false,
  'upload_thumb_w' => '',
  'upload_thumb_h' => '',
  'upload_thumb_pos' => '1',
  'upload_water' => false,
  'upload_water_pct' => '',
  'upload_water_pos' => '0',
  'upload_water_img' => '',
  'upload_ftp' => false,
  'upload_ftp_del' => '0',
  'upload_ftp_host' => '',
  'upload_ftp_user' => '',
  'upload_ftp_pass' => '',
  'upload_ftp_port' => '',
  'upload_ftp_dir' => '',
  'upload_http_prefix' => '',
  'play_server' => 
  array (
    'ting' => 'ting.gxlcms.com',
  ),
  'news_pic' => '1',
  'cai_baidutui' => '1',
  'baidu_tui' => '',
  'play_collect' => true,
  'rand_tag' => '1',
  'play_collect_name' => '0',
  'play_collect_time' => '2',
  'rand_hits' => '10',
  'rand_updown' => '10',
  'rand_gold' => '1',
  'rand_golder' => '10',
  'user_second' => '',
  'user_gbnum' => '',
  'user_cmnum' => '',
  'user_replace' => '',
  'play_collect_content' => 
  array (
    0 => '',
  ),
  'play_second' => 0,
  'user_gbcm' => false,
  'html_cache_time' => 0,
  'html_cache_rules' => 
  array (
    'home:index:index' => 
    array (
      0 => '{:action}',
      1 => 3600,
    ),
    'home:ting:show' => 
    array (
      0 => '{:controller}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:news:show' => 
    array (
      0 => '{:controller}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:ting:read' => 
    array (
      0 => '{:controller}_{:action}/{name|get_small_id_by_name}{id|get_small_id}/{name|gettingidmd}{id|getmd5}',
      1 => 3600,
    ),
    'home:news:read' => 
    array (
      0 => '{:controller}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:ting:play' => 
    array (
      0 => '{:controller}_{:action}/{name|get_small_id_by_name}{id|get_small_id}/{name|gettingid}{id}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:my:show' => 
    array (
      0 => '{:controller}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:special:read' => 
    array (
      0 => '{:controller}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:story:read' => NULL,
    'home:story:show' => NULL,
    'home:actor:show' => NULL,
    'home:actor:read' => NULL,
  ),
);
?>
