<?php
define('sitetitle','zzcms专业做招商网的程序源码') ;//SiteKeywords
define('sitekeyword','zzcms专业做招商网的程序源码') ;//SiteKeywords
define('sitedescription','zzcms专业做招商网的程序源码') ;//sitedescription
define('zslisttitle','招商') ;//zslisttitle
define('zslistkeyword','招商') ;//zslistkeyword
define('zslistdescription','招商') ;//zslistdescription
define('zsshowtitle','招商') ;//zsshowtitle
define('zsshowkeyword','招商') ;//zsshowkeyword
define('zsshowdescription','招商') ;//zsshowdescription
define('dllisttitle','代理') ;//dllisttitle
define('dllistkeyword','代理') ;//dllistkeyword
define('dllistdescription','代理') ;//dllistdescription
define('dlshowtitle','代理') ;//dlshowtitle
define('dlshowkeyword','代理') ;//dlshowkeyword
define('dlshowdescription','代理') ;//dlshowdescription
define('zhlisttitle','展会') ;//zhlisttitle
define('zhlistkeyword','展会') ;//zhlistkeyword
define('zhlistdescription','展会') ;//zhlistdescription
define('zhshowtitle','展会') ;//zhshowtitle
define('zhshowkeyword','展会') ;//zhshowkeyword
define('zhshowdescription','展会') ;//zhshowdescription
define('zxlisttitle','资讯') ;//zxlisttitle
define('zxlistkeyword','资讯') ;//zxlistkeyword
define('zxlistdescription','资讯') ;//zxlistdescription
define('zxshowtitle','资讯') ;//zxshowtitle
define('zxshowkeyword','资讯') ;//zxshowkeyword
define('zxshowdescription','资讯') ;//zxshowdescription
define('ztlisttitle','专题') ;//ztlisttitle
define('ztlistkeyword','专题') ;//ztlistkeyword
define('ztlistdescription','专题') ;//ztlistdescription
define('ztshowtitle','专题') ;//ztshowtitle
define('ztshowkeyword','专题') ;//ztshowkeyword
define('ztshowdescription','专题') ;//ztshowdescription
define('companylisttitle','企业') ;//companylisttitle
define('companylistkeyword','企业') ;//companylistkeyword
define('companylistdescription','企业') ;//companylistdescription
define('companyshowtitle','企业') ;//companyshowtitle
define('companyshowkeyword','企业') ;//companyshowkeyword
define('companyshowdescription','企业') ;//companyshowdescription
define('pplisttitle','品牌') ;//pplisttitle
define('pplistkeyword','品牌') ;//pplistkeyword
define('pplistdescription','品牌') ;//pplistdescription
define('ppshowtitle','品牌') ;//ppshowtitle
define('ppshowkeyword','品牌') ;//ppshowkeyword
define('ppshowdescription','品牌') ;//ppshowdescription
define('joblisttitle','招聘') ;//joblisttitle
define('joblistkeyword','招聘') ;//joblistkeyword
define('joblistdescription','招聘') ;//joblistdescription
define('jobshowtitle','招聘') ;//jobshowtitle
define('jobshowkeyword','招聘') ;//jobshowkeyword
define('jobshowdescription','招聘') ;//jobshowdescription
define('baojialisttitle','baojialisttitle') ;//baojialisttitle
define('baojialistkeyword','baojialistkeyword') ;//baojialistkeyword
define('baojialistdescription','baojialistdescription') ;//baojialistdescription
define('baojiashowtitle','baojiashowtitle') ;//baojiashowtitle
define('baojiashowkeyword','baojiashowkeyword') ;//baojiashowkeyword
define('baojiashowdescription','baojiashowdescription') ;//baojiashowdescription
define('wangkanlisttitle','wangkanlisttitle') ;//wangkanlisttitle
define('wangkanlistkeyword','wangkanlistkeyword') ;//wangkanlistkeyword
define('wangkanlistdescription','wangkanlistdescription') ;//wangkanlistdescription
define('wangkanshowtitle','wangkanshowtitle') ;//wangkanshowtitle
define('wangkanshowkeyword','wangkanshowkeyword') ;//wangkanshowkeyword
define('wangkanshowdescription','wangkanshowdescription') ;//wangkanshowdescription
define('asklisttitle','问答') ;//asklisttitle
define('asklistkeyword','问答') ;//asklistkeyword
define('asklistdescription','问答') ;//asklistdescription
define('askshowtitle','问答') ;//askshowtitle
define('askshowkeyword','问答') ;//askshowkeyword
define('askshowdescription','问答') ;//askshowdescription
?>